### ISSUE TITLE
 Missing "data-models" package

### ISSUE THREAD

**Issue by norfeus** [LinOTP/selfservice#1]
Hi! Now I’m translating this selfservice into another language, I encountered a problem with the inaccessibility of the repository in which the @linotp/data-models package is located. The absence of this package makes it impossible to build the project and, accordingly, translate it into another language.

Full link to the package from the yarn.lock file:
"https://gitbox.corp.keyidentity.com/api/v4/projects/381/packages/npm/@linotp/data-models/-/@linotp/data-models-1.2.1.tgz#ff231e9e74ae955a5a546a0b0d217bd8248d2fd4"

Where can I access this package or the package itself?

**Comment by lukengda** [comment]
Hi @norfeus - i am working on getting the repo published to github.

**Comment by devel-linotp** [comment]
Hi @norfeus, i noticed, that the github mirror was not correctly syncing. We have since fixed this issue and you now no longer need the data-models package. Thanks for your patience!
